### ISSUE TITLE
how many cells/bulk data do I need?

### ISSUE THREAD

**Issue by xiaonian92** [JxTang-bioinformatics/CaMelia#1]
Hi, thanks for the great software! I have two questions: 
1) How many known data should I use as an input if I want to impute about 50 cells? The coverage of my target cells are extremely heterogeneous which varies 15~75%. 
2) And how to select the input known data? My target cells are from several developmental stages, I guess I need to gather cells from the same stages, but it's hard.  
Thanks again!

**Comment by JxTang-bioinformatics** [comment]
This issue has been resolved through email communication.
