### ISSUE TITLE
Worrisome handling of NaNs of Locally paired similarity feature

### ISSUE THREAD

**Issue by gdewael** [JxTang-bioinformatics/CaMelia#3]
After running the preprocessing on the example data, about one in ten samples of `cell0` has a NaN as locally paired similarity feature. If I understand correctly this is because of the imposed threshold only allowing scores above 0.8.

Presumably, CpG sites with a NaN for this feature are 'hard' to predict, because their neighboring methylation sites did not have an obvious correlation with those of other cells. If I am right, in `model_TrainingandImputing.py` you delete these samples by doing `dataset_train = dataset_train.dropna(axis=0,how='any')`. This renders your model to only train on and evaluate 'easy-to-predict' CpG sites.

Regarding your publication, this introduces a bias which might skew performance evaluation in favor of this method. I remain with two questions:
1. Could you elaborate on this design choice? The threshold on the locally paired similarity feature seems very arbitrary and overengineered. Are you sure you have tuned your model with the abovementioned considerations in mind?
2. In your comparison to other methods such as DeepCpG, did you take these facts into account?

**Comment by JxTang-bioinformatics** [comment]
Hi gdewael,

Thanks for your question. 

The loci you considered that do not have a locally paired similarity feature are not in the imputation range of CaMelia.
In terms of model comparison, we evaluated in detail the impact of the three types of features on the model performance in Figure3a as well as in TableS2, and we can see that the introduction of the locally paired similarity feature can significantly improve the performance (compared to the neighboring methylation feature).

We did not observe in our experiments that the loci with this feature are  'easy-to-predict' loci. In addition, we did not deliberately observe in our experiments whether loci with this feature are "easy-to-predict" loci. The introduction of the locally paired similarity feature also provided a significant gain if the neighboring methylation feature was used to assess whether a locus was an easily predicted locus (e.g., from 0.9261 to 0.9707 on the mESC data set).

Thank you again for your careful reading, and I hope this answers your confusion.
